name: Block Unwanted Users

on:
  push:
    branches: [ main, ai-integration-complete ]
  pull_request:
    branches: [ main, ai-integration-complete ]

jobs:
  block-user:
    runs-on: ubuntu-latest
    steps:
      - name: Check commit author
        run: |
          # Get the commit author
          AUTHOR_EMAIL=$(git log -1 --pretty=format:"%ae")
          AUTHOR_NAME=$(git log -1 --pretty=format:"%an")
          
          echo "Commit author: $AUTHOR_NAME <$AUTHOR_EMAIL>"
          
          # Block specific email patterns
          if [[ "$AUTHOR_EMAIL" == *"questionpro.com"* ]] || [[ "$AUTHOR_EMAIL" == *"qp"* ]]; then
            echo "❌ BLOCKED: Unwanted email pattern detected: $AUTHOR_EMAIL"
            echo "This commit has been blocked due to unwanted email pattern."
            exit 1
          fi
          
          # Block specific name patterns
          if [[ "$AUTHOR_NAME" == *"ritwik-yadav-qp"* ]] || [[ "$AUTHOR_NAME" == *"questionpro"* ]]; then
            echo "❌ BLOCKED: Unwanted name pattern detected: $AUTHOR_NAME"
            echo "This commit has been blocked due to unwanted name pattern."
            exit 1
          fi
          
          echo "✅ Author check passed: $AUTHOR_NAME <$AUTHOR_EMAIL>"
